# Generated by Django 4.2.29 on 2026-08-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edithistory',
            name='operation',
            field=models.CharField(choices=[('translate', ' Translation'), ('grammar', ' Grammar Check'), ('plagiarism', ' Plagiarism Check'), ('summarize', ' Summarization'), ('speech', ' Speech to Text')], max_length=20),
        ),
    ]
